# MAKEFILE

target:
	@ clear
	@ rm -f exe04
	@ g++ -Wall -o exe04 solution_noclass.cpp
	@ ./exe04

target_class:
	@ clear
	@ rm -f exe04
	@ g++ -Wall -o exe04 solution_class.cpp
	@./exe04

clean:
	@ clear
	@ rm -f exe04
	@ echo "All shiny..."