solution_PIPES:
	@clear
	@rm -f exeA
	@gcc -Wall -o exeA solution_PIPES.c
	@./exeA

solution_FIFOS:
	@clear
	@rm -f exeB
	@gcc -Wall -o exeB solution_FIFOS.c
	@./exeB

solution_QUEUE:
	@clear
	@rm -f exeC
	@gcc -Wall -o exeC solution_QUEUE.c
	@./exeC

clean:
	@clear
	@rm -f exe*
	@echo "All shiny..."