DIR="/Users/davidearcolini/Desktop/PoliTo/OperatingSystem/Labs/LAB08/E01/testdir"
FUN="test()"
OUT="/Users/davidearcolini/Desktop/PoliTo/OperatingSystem/Labs/LAB08/E01/outfile.txt"

target:
	@clear
	@./script_L08E01.sh $(DIR) $(FUN) $(OUT)
	@echo "OUTPUT: "
	@cat $(OUT)
	@rm $(OUT)