# MAKEFILE
#


target:
	@ clear 
	@ rm -f stack.o
	@ rm -f test_stack
	@ g++ -Wall -o stack.o -c Stack.cpp
	@ g++ -Wall -o test_stack main.cpp stack.o
	@ ./test_stack

clean:
	@ clear 
	@ rm -f stack.o
	@ rm -f test_stack
	@ echo "All shiny..."
